// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: exercise_rr_samples.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// RR.BPB=PbExerciseRRIntervals

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Data_PbRROffline {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Start time / offset from the beginning of the exercise
  var startTime: PbDuration {
    get {return _startTime ?? PbDuration()}
    set {_startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  var hasStartTime: Bool {return self._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  mutating func clearStartTime() {self._startTime = nil}

  /// Duration of the offline period
  var timeInterval: PbDuration {
    get {return _timeInterval ?? PbDuration()}
    set {_timeInterval = newValue}
  }
  /// Returns true if `timeInterval` has been explicitly set.
  var hasTimeInterval: Bool {return self._timeInterval != nil}
  /// Clears the value of `timeInterval`. Subsequent reads from it will return its default value.
  mutating func clearTimeInterval() {self._timeInterval = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _startTime: PbDuration? = nil
  fileprivate var _timeInterval: PbDuration? = nil
}

///
///
///RR intervals of the exercise.
///
///! All fields are required.
struct Data_PbExerciseRRIntervals {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// rr intervals in milliseconds
  var rrIntervals: [UInt32] = []

  /// Contains information about periods when there has not been a connection to a rr interval sensor
  ///
  /// rr_intervals fields will be always written into the file and offline fields are additional
  ///
  /// information for marking periods as offline periods
  var rrSensorOffline: [Data_PbRROffline] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "data"

extension Data_PbRROffline: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PbRROffline"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "start_time"),
    2: .standard(proto: "time_interval"),
  ]

  public var isInitialized: Bool {
    if self._startTime == nil {return false}
    if self._timeInterval == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularMessageField(value: &self._startTime)
      case 2: try decoder.decodeSingularMessageField(value: &self._timeInterval)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if let v = self._startTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }
    if let v = self._timeInterval {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Data_PbRROffline, rhs: Data_PbRROffline) -> Bool {
    if lhs._startTime != rhs._startTime {return false}
    if lhs._timeInterval != rhs._timeInterval {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Data_PbExerciseRRIntervals: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PbExerciseRRIntervals"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "rr_intervals"),
    2: .standard(proto: "rr_sensor_offline"),
  ]

  public var isInitialized: Bool {
    if !SwiftProtobuf.Internal.areAllInitialized(self.rrSensorOffline) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeRepeatedUInt32Field(value: &self.rrIntervals)
      case 2: try decoder.decodeRepeatedMessageField(value: &self.rrSensorOffline)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.rrIntervals.isEmpty {
      try visitor.visitPackedUInt32Field(value: self.rrIntervals, fieldNumber: 1)
    }
    if !self.rrSensorOffline.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rrSensorOffline, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Data_PbExerciseRRIntervals, rhs: Data_PbExerciseRRIntervals) -> Bool {
    if lhs.rrIntervals != rhs.rrIntervals {return false}
    if lhs.rrSensorOffline != rhs.rrSensorOffline {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
